### ISSUE TITLE
cannot make request when authorization is enforced

### ISSUE THREAD

**Issue by sn1987a** [alexatiks/keycloak-postman-pre-request#2]
Dear Alexatiks,

I followed the authorization quickstart of keycloak in here: https://www.keycloak.org/docs/latest/authorization_services/#_getting_started_overview. This allows me a create a sample jee webapp. After deploying, I can login without any problem in Firefox or Chrome.

But when I try to request the same page ( http://localhost:8080/app-authz-vanilla ) in Postman by following your tutorial, I always have a 403 Forbidden code. In the console, the script managed to get an access token. That access token is then passed into the Authorization Header as Bearer for the final get. But that GET request fails.

The only difference between your config and my config in KeyCloak is "Authorization Enabled" = true. But even when I disable it, I still get an error.

Can you check why it doesn't work ?

Best regards,
Damien

**Comment by sn1987a** [comment]
sorry, I think I found out the issue. It's not because of keycloak but my webapp. Sorry again for any disturbance

**Comment by alexatiks** [comment]
I'm glad that you found out the issue :)
